### ISSUE TITLE
XS12 erases all settings of other businesses managed with the same browser; doesn't work with HR dept.

### ISSUE THREAD

**Issue by TeaMike** [XiozZe/XioScript#44]
After doing a couple of test settings at my main company i decided using it on a test clone today, which only has a few subdivisions and no HR service. 

The script executed but threw back a long list of errors like this example:
"Subdivision 12345678 is missing from the company. Options have been erased from the Local Storage".

Checking back at my main company, some of the entries are still there but others aren't. 

When running the script again at the clone, the same errors appear again, even with the same subdivision IDs, meaning the script didn't erase all those entries.

Note that i executed XS 12.0.13 only on the 3 offices browsed, these other subdivisions aren't even offices.

Another issue i found is the salary setting:  it doesn't consider the training in place, the subdivision will fail to achieve 100% efficiency during the update if both settings are used simultaneously.

**Comment by XiozZe** [comment]
It seems that I did not update this remove subdivision function with the realm separation. Therefore, it tried to delete an entry from the LocalStorage in the old syntax. Fixed in 12.0.14.

I don't care that the script does not work on clones. I don't like players that use clones anyway. Using the function on the clone should erase ALL options from the main account.

Salary setting does indeed not consider training. With 4 training days, I have no clue what the qualification of the employees tomorrow will be. Even with just one day I lose the value after the training is set: meaning that I would have to store it and I don't like store values. So I am aware of the problem but I have no clue to solve it. Just use the "target salary" instead of the "maximum salary" and 90% of the cases should be fine.

**Comment by TeaMike** [comment]
Salary/holidays testing at MICO: no can do because the script doesn’t set the value into the correct field with HR management active.

Then, XS salary and training functions are in conflict with maxed out qualification growth so its a bit unclear for who it would actually be useful. 

It could be fixed by grabbing the "end of training" value at training start and consulting another value stored in the local storage for setting the correct salary.

Clones and/or multiple players on the same browser: Russia definitely outshines the west in terms of a liberal view and user-friendliness on this one.

**Comment by XiozZe** [comment]
Wasn't the top manager without bonuses the maximum growth? Remember, target = without bonuses (it's the target value for maximum growth) and maximum = with bonuses (above this may inflict the top manager efficiency). So target salary + training = maximum growth and training with top manager eff. 100%.

If using clones is liberal, I'm a communist: no love for clones.
