### ISSUE TITLE
Different values of target and maximun values in factories

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#70]
My qualification in production is 17, with a bonus of +1, so maximum shall be based on 18.

According to XioScript:

Target value 34000
Maximum value 37800

However, according to the [wiki of virtonomics](http://wiki.virtonomics.com/index.php/Qulification_requirements) the values should be:

Target value 37348
Maximum value 41539

Is there something I am missing?

**Comment by XiozZe** [comment]
The values are based of the tables of [DeMonyan](http://calc.atlantis-corp.ru/top3.php).
Whether or not the actual values work: try to overfill a factory with workers, so that you know for sure that the top manager efficiency takes a hit. Now check the forecast and compare it with my "Top Manager Efficiency". If these two values are exactly the same, you know that my values are right.

**Comment by Trebia** [comment]
Will double check and give you feedback, will take me some time...

**Comment by TeaMike** [comment]
are TM values the same as in previous XS versions (e.g. 10.xx), or have you changed them?
The 10.xx where totally on the spot

**Comment by XiozZe** [comment]
Except the overflow function values, everything else should be exactly the same.

**Comment by Trebia** [comment]
Confirmed. The script is fully consisten.
